---
- name: Email Notication on Failure 
  hosts: localhost
  
  tasks:
    - name: Email using Gmail smtp server
      mail:
        host: smtp.gmail.com
        port: 587
        username: jagendra.khadka@gmail.com
        password: Simran#321
        to: pushpendra.s.bhandari07@gmail.com
        from: jagen.kh@gmail.com
        subject: WorkFlow Failed
        body: 'One of the tasks in the workflow has failed.'
      delegate_to: localhost
...

