---
- name: Email Notication on Failure 
  hosts: localhost
  become: true
  become_method: enable
  #vars_files: /home/tmp/secret.yml

  
  tasks:
    - name: Email using Gmail smtp server
      mail:
        host: smtp.gmail.com
        port: 587
        username: jagendra.khadka@gmail.com
        password: Simran#321
        to: jagen.kh@gmail.com
        from: no-reply@citi.com
        subject: WorkFlow Failed
        body: 'One of the tasks in the workflow has failed.'
      delegate_to: localhost
...

