---
- name: Start Cluster
  hosts: localhost
  become: true
  become_user: admin
     
  tasks:
  - name: Start Cluster
    debug:
      msg: "The Cluster has been successfully Started."
...
