---
- name: Start Cluster
  hosts: localhost
  become: true
  vars:
    host= "localhost"
  
  tasks:
  - name: Start Cluster
    debug:
      msg: "The Cluster {{host}} has been successfully Started."
...