---
- name: Stop Cluster
  hosts: localhost
  become: true
  vars:
    host= "localhost"
  
  tasks:
  - name: Stop Cluster
    debug:
      msg: "The Cluster {{host}} has been successfully Stopped."
...