---
- name: Upgrade Cluster
  hosts: 192.168.1.122
  #become: true
  #vars:
  #  host= "localhost"
  
  tasks:
  - name: Append text to the file
    lineinfile:
      path: /home/tmp/append.txt
      line: "the cluster upgraded  successfully on {{ ansible_date_time.iso8601 }} ."
      insertafter: EOF
      create: true

  - name: Cluster Upgrade
    debug:
      msg: "The Cluster has been successfully upgraded on {{ ansible_date_time.iso8601 }} ."
...
